#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_101
export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR
nohup java  -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=30 -XX:MaxHeapFreeRatio=50 -Xms384m -Xmx800m -jar target/*.war --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --spring.profiles.active=prod &
